server:
  port: ${SERVER_PORT:8082}

users-service:
  default-password: ${DEFAULT_PASSWORD:Itest@123}
  encryption-key: ${ENCRYPT_KEY:d2hzLWhleS1rcmlzaG5hLXJhbWEtcmFtYS1yYW1h} # base64 key

spring:
  application.name: users-service

  ############################### Database ############################
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  #  jpa.show-sql: true

  # ref: https://contribute.liquibase.com/extensions-integrations/directory/integration-docs/springboot/configuration/
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
  #   rollback-file: rollback.sql

logging:
  level:
    liquibase: DEBUG
