server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

users-service:
      # bcrypt hashed password: $2a$10$tSepBpJKxkvJnkNR45miqO/c55NLFw49YWx9Z6jqZzHkxwbvkMI3i
  encryption-key: ${ENCRYPT_KEY:gd3jMu1Asdr/9mrQ+Pdvgo1K9tO10n7hu6StlRpDd94=} # base64 key
  hashSecret: ${HASH_SECRET:9s4gZDGFUESlt7+96NEyDasV22OQFSoD9H32f2bS7fo=} # base64 recommended

spring:

  application.name: users-service
  main:
    banner-mode: off
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  profiles:
    active: local


  ############################### Database ############################
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        type:
          contributors: org.springframework.data.jpa.repository.config.BeanContainerBeanFactoryAdvisingBeanPostProcessor

  #  jpa.show-sql: true

  # ref: https://contribute.liquibase.com/extensions-integrations/directory/integration-docs/springboot/configuration/
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
  #   rollback-file: rollback.sql

logging:
  level:
    liquibase: DEBUG
